{
 "title": "My Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ACX7509-2: Packets per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket:\"poc\")\n |> range(start: -1h)\n |> filter(fn: (r) => r.source == \"acx7509-2\" and r.name =~ /ae*/ and r.index == \"0\" and r._field =~ /subinterfaces\\/subinterface\\/state\\/counters\\/(in|out)_pkts/ )\n |> derivative(nonNegative: true)\n |> aggregateWindow(every: v.windowPeriod, createEmpty: false, fn: mean)\n |> yield (name: \"mean\")"
    }
   ]
  },
  {
   "title": "MX204-83: Packets per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket:\"poc\")\n |> range(start: -1h)\n |> filter(fn: (r) => r.source == \"mx204-83\" and r.index == \"0\" and r.name =~ /^et-*/ and r._field =~ /subinterfaces\\/subinterface\\/state\\/counters\\/(in|out)_pkts/ )\n |> derivative(nonNegative: true)\n |> aggregateWindow(every: v.windowPeriod, createEmpty: false, fn: mean)\n |> yield (name: \"mean\")"
    }
   ]
  },
  {
   "title": "ACX7509-2: Bits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket:\"poc\")\n |> range(start: -10h)\n |> filter(fn: (r) => r.source == \"acx7509-2\" and r.name =~ /ae*/ and r.index == \"0\" and r._field =~ /subinterfaces\\/subinterface\\/state\\/counters\\/(in|out)_octets/ )\n |> map(fn: (r) => ({r with _value: r._value * 8}))\n |> derivative(nonNegative: true)\n |> aggregateWindow(every: v.windowPeriod, createEmpty: false, fn: mean)\n |> yield (name: \"mean\")"
    }
   ]
  },
  {
   "title": "MX204-83: Bits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket:\"poc\")\n |> range(start: -10h)\n |> filter(fn: (r) => r.source == \"mx204-83\" and r.name =~ /et-*/ and r.index == \"0\" and r._field =~ /subinterfaces\\/subinterface\\/state\\/counters\\/(in|out)_octets/ )\n |> map(fn: (r) => ({r with _value: r._value * 8}))\n |> derivative(nonNegative: true)\n |> aggregateWindow(every: v.windowPeriod, createEmpty: false, fn: mean)\n |> yield (name: \"mean\")"
    }
   ]
  }
 ]
}